force-app/main/default/objects/Account/fields/Total_Investment__c.field-meta.xml
<CustomField>
    <fullName>Total_Investment__c</fullName>
    <label>Total Investment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>Exp-{0000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ExpenseTriggerHandlerHelper.cls
public class ExpenseTriggerHandlerHelper {
    
    public static void updateExpenseOnAccount(Set<Id> contactIds){
        List<Account> updateAccList = new List<Account>();
        Set<Id> accIds = new Set<Id>();


        for(Contact con :[Select Id, AccountId from Contact where Id IN :contactIds]){
            accIds.add(con.AccountId);
        }
        		
        for(AggregateResult agr : [Select Sum(Amount__c) total,Contact__r.AccountId accId from Expense__c where Contact__r.AccountId IN :accIds group by Contact__r.AccountId]){	
            Account accObj = new Account();
            accObj.Id = (Id)agr.get('accId');
            accObj.Total_Investment__c = (Decimal) agr.get('total');
            updateAccList.add(accObj);
        }

        if(!updateAccList.isEmpty()){
            Database.update(updateAccList,false);
        }
    }
}